### PR TITLE
Add Union support

### PR DESCRIPTION
**Pull request by mikee47**
This PR adds support for unions and for defined types using JSONSchema `$ref`.

https://json-schema.org/understanding-json-schema/structuring#dollarref

This allows types to be defined within the `$defs` section of the schema and re-used.

This is leveraged to support `Union` types via the `oneOf` schema keyword.
The `test` application contains an example of this in the `test-config-union.cfgdb` schema. It is used in the `Updates` test module.

## Union structures

Like a regular C++ `union`, a `ConfigDB::Union` object has one or more object types overlaid in the same storage space. The size of the object is therefore governed by the size of the largest type stored. A `uint8_t` property tag indicates which type is stored.

The code generator produces a `get` method for each type of object which can be stored. The application is responsible for checking which type is present via `getTag`; if the wrong method is called, a runtime assertion will be generated.

The corresponding Union Updater class has a `setTag` method. This changes the stored object type and initialises it to default values. This is done even if the tag value doesn't change so can be used to 'reset' an object to defaults.

## Store child objects as properties

Instead of storing a separate list of `ObjectInfo` pointers for contained objects, these are now included in the object properties `PropertyInfo` list. This change is necessary because a type may be used in several places with different names.

TODO:

* [x] Add non-const `getXXX` methods for Updater
* [x] Verify use for arrays of `Union`
* [x] Verify use for unions containing arrays
* [x] Verify recursive (self-referencing) use of `$defs`, e.g. `Color` containing an array of `Color`.
* [x] Document use of `$ref` and `$defs`, clarifying difference in behaviour between *object definitions* and *property templates*

### CODE REVIEW

**Comment by pljakobs** [comment]
this is getting crazy powerful!
So basically, this allows to better structure the schema. Does $ref work multi level? So could I have  this to define an abstract `color` data item and use that wherever I deal with color (knowing that I would have to distinguish what 'type' it is at runtime)
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "color":{
        "$ref":"#/$defs/color"
    }
  },
  "$defs": {
    "color": {
      "oneOf": [
        {
          "$ref": "#/$defs/RGB"
        },
        {
          "$ref": "#/$defs/HSV"
        },
        {
          "$ref": "#/$defs/RAW"
        }
      ],
    "RGB": {
      "type": "object",
      "properties": {
        "red": {
          "type": "integer",
          "default": 100,
          "minimum": 0,
          "maximum": 1023
        },
        "green": {
          "type": "integer",
          "default": 100,
          "minimum": 0,
          "maximum": 1023
        },
        "blue": {
          "type": "integer",
          "default": 100,
          "minimum": 0,
          "maximum": 1023
        }
      }
    },
    "HSV": {
      "type": "object",
      "properties": {
        "hue": {
          "type": "integer",
          "default": 0,
          "minimum": 0,
          "maximum": 359
        },
        "saturation": {
          "type": "integer",
          "default": 100,
          "minimum": 0,
          "maximum": 100
        },
        "value": {
          "type": "integer",
          "default": 100,
          "minimum": 0,
          "maximum": 100
        }
      }
    },
    "RAW": {
      "type": "object",
      "properties": {
        "red": {
          "type": "integer",
          "default": 800,
          "minimum": 0,
          "maximum": 1023
        },
        "green": {
          "type": "integer",
          "default": 500,
          "minimum": 0,
          "maximum": 1023
        },
        "blue": {
          "type": "integer",
          "default": 200,
          "minimum": 0,
          "maximum": 1023
        },
        "warm-white": {
          "type": "integer",
          "default": 1023,
          "minimum": 0,
          "maximum": 1023
        },
        "cold-white": {
          "type": "integer",
          "default": 0,
          "minimum": 0,
          "maximum": 1023
        }
      }
    }
  }
}
```

**Comment by mikee47** [comment]
> Does $ref work multi level?

Yes, but need to add tests for recursive use, for arrays of union and for unions containing arrays. Plus any other weird combos.

**Comment by mikee47** [comment]
NB. As Hue appears to be expressed in degrees you could define a type for that...

**Comment by pljakobs** [comment]
> Yes, but need to add tests for recursive use, for arrays of union and for unions containing arrays. Plus any other weird combos.
an array of unions would perfectly match my "presets" array. I did not expect this to be so easy. 

> NB. As Hue appears to be expressed in degrees you could define a type for that...
yes, but frankly, I'm not thrilled about changing type throughout the project, especially as the RGBWWLed library is technically outside this project (it does do all the color computations and drives the LEDs) and may be used by other projects. There, it's defined `int` and, for now, changing that interface is not something I want to do.

**Comment by mikee47** [comment]
> changing type throughout the project

It needs documenting, but when used for simple (non-object) properties, `$ref` defines a base *template* to use. It doesn't define a C++ type. I've done this for some types in `basic-config.cfgdb`. For example:

```json
"Pin": {
  "type": "integer",
  "minimum": 0,
  "maximum": 63
}
```
It's used in the *channels* definition:

```json
"pin": {
  "$ref": "#/$defs/Pin",
  "default": 13
},
```
Which gets expanded by the code generator into this:

```json
"pin": {
  "type": "integer",
  "minimum": 0,
  "maximum": 63,
  "default": 13
},
```
Just saves a lot of duplication and makes the schema more readable.

If/when I implement custom types then we'd need to add maybe a `ctype` annotation in order to convert this into an actual type.

**Comment by pljakobs** [comment]
at this point, this seems to not correctly handle the string with control characters.

```
{"purpose":"general","current-limit":400,"garbage":"This is potentially
a problem
string /* with stuff inside it */"}
```
Message from Firefox:
```
SyntaxError: JSON.parse: bad control character in string literal at line 1 column 795 of the JSON data
```

**Comment by mikee47** [comment]
The Sming formatter code has been updated, can you check you're on the latest develop? My `feature/json-config` branch has been rebased off that.

**Comment by pljakobs** [comment]
ah, that fixed it! thank you!

**Comment by pljakobs** [comment]
right now, compound unions are not yet implemented, right? So this does not yet work? Or am I misunderstanding the schema syntax here? Should the objects be in `{ }` ?
```
   "RGB": {
      "r":{
        "type": "integer",
        "minimum": 0,
        "maximum": 1023
      },
      "g":{
        "type": "integer",
        "minimum": 0,
        "maximum": 1023
      },
      "b":{
        "type": "integer",
        "minimum": 0,
        "maximum": 1023
      }
    },
    "HSV":{
      "h":{
        "type": "integer",
        "minimum": 0,
        "maximum": 359
      },
      "s":{
        "type": "number",
        "minimum": 0,
        "maximum": 100
      },
      "v":{
        "type": "mumber",
        "minimum": 0,
        "maximum": 100
      }
    },
    "RAW": {
      "r": {
        "type": "integer",
        "minimum": 0,
        "maximum"
      },
      "g": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1023
      },
      "b": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1023
      },
      "cw": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1023
      },
      "ww": {
        "type": "integer",
        "minimum": 0,
        "maximum": 1023
      }
    }
    "color":{
      "oneOf": [
      "$ref":"#/$defs/RGB",
      "$ref":"#/$devs/HSV",
      "$ref":"#/$devs/RAW"
      ]
    }
```

**Comment by pljakobs** [comment]
defining the pins as a $ref with minimum and maximum gave me an idea - the different controllers have different available pwm pins / limits - could the pins be limited to a oneOf as well, so basically a non contiguous list of individual pins and then indexed so that the application can select the correct one for the architecture? Also, would the application be able to pull that list in order to give it to the front end for a select box? (this is by no means necessary, just a thought)

**Comment by mikee47** [comment]
> ... could the pins be limited to a oneOf as well, so basically a non contiguous list of individual pins and then indexed so that the application can select the correct one for the architecture? Also, would the application be able to pull that list in order to give it to the front end for a select box? (this is by no means necessary, just a thought)

I'm not quite sure what you mean. Can you give an example?

**Comment by pljakobs** [comment]
I was thinking of a list like 
```
Pins:{
  "type": "integer",
  "oneOf": [2,5,7,8,10,12,13]
}
```
but this list would be different for the different platforms, so it would push platform dependet configuration into the schema, not sure how good that idea is.

**Comment by mikee47** [comment]
So by `platform` do you mean esp32, esp8266, etc. or something else?

**Comment by mikee47** [comment]
Would the list be the same length for each platform?

**Comment by mikee47** [comment]
Is this perhaps the sort of thing you're after?

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "esp8266": {
            "$ref": "#/$defs/Platform",
            "store": true
        },
        "esp32": {
            "$ref": "#/$defs/Platform",
            "store": true
        },
        "rp2040": {
            "$ref": "#/$defs/Platform",
            "store": true
        }
    },
    "$defs": {
        "Platform": {
            "type": "object",
            "properties": {
                "pins": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/Pin"
                    }
                }
            }
        },
        "Pin": {
            "type": "integer",
            "minimum": 0,
            "maximum": 63
        }
    }
}
```

**Comment by pljakobs** [comment]
> So by platform do you mean esp32, esp8266, etc. or something else?

yes, I should have said `Architecture`

 > Would the list be the same length for each platform?

no, different architectures may have different numbers of available pins for, e.g. PWM or COM or whatever. 

> Is this perhaps the sort of thing you're after?

no, I thought about the availability of pins on a specific Arch / Device (with Device being a design around a controller of a specific Architecture). 
My current Hardware supports driving LED strips on pins 4, 5, 12, 13 and 14 on the ESP8266, the design I have for the ESP32C3 has a different set of pins. I was thinking that, if we have range checks, there may also be a way to enforce that the value can only be one of those. 
But then, I think it's a very narrow use case for that database to limit the possible values to an array like that and easier done in application code.

**Comment by mikee47** [comment]
> ... if we have range checks, there may also be a way to enforce that the value can only be one of those.

Sounds a little counter-intuitive but (JSONSchema enum)[https://json-schema.org/understanding-json-schema/reference/enum] is probably the right keyword for this use.

> But then, I think it's a very narrow use case for that database to limit the possible values to an array like that and easier done in application code.

This could be another use-case for *enum* (issue #13). For strings:

```json
"color-value": {
    "type": "string",
    "enum": ["red", "green", "blue"],
    "ctype": "uint8"
}
```

The generated API allows applications to use numeric values 0, 1, 2 for "red", "green", "blue" and ConfigDB deals with the conversion. It's a bit like `HashMap<uint8_t, String>`. For your use-case:

```json
"pwm-pins": {
    "oneOf": [
        {
            "$ref": "#/$defs/pwm-pins-esp8266"
        },
        {
            "$ref": "#/$defs/pwm-pins-esp32"
        }
    ]
},
"$defs": {
    "pwm-pins-esp8266": {
        "$ref": "#/$defs/Pin",
        "enum": [2,5,7,8,10,12,13]
    },
    "pwm-pins-esp32": {
        "$ref": "#/$defs/Pin",
        "enum": [8,10,25,4,5,6,7]
    }
}
```

The API would use the index (0 - 5) but store the actual pin, so like `HashMap<uint8_t, uint8_t>`.

Because the hardware is fixed it does actually make sense to have this information as part of the schema.

**Comment by mikee47** [comment]
Are you aware of `make pinmenu` ?

**Pull request merged**
